### ISSUE TITLE
What does it mean when PositionedGlyph::draw call back give value of negative float?

### ISSUE THREAD

**Issue by bombless** [redox-os/rusttype#26]
I tried a Chinese character "试" and the third argument of the call back gives some negative value like

```
-0.3671875
-0.3671875
-0.3671875
-0.50561523
-0.625
-0.01739502
-0.37109375
-0.37109375
```

I'm using a font file "simsunb.ttf" from Windows 10.

**Comment by bombless** [comment]
I updated to rusttype 0.2.1 but still no good

**Comment by bombless** [comment]
I run the program from another computer with font "yumin.ttf" and some CJK characters like "你好" is fine, while "试" still prints a square. "simsunb.ttf" cannot draw "你好" on this computer, as I tried earlier.

**Comment by dylanede** [comment]
Negative values from `PositionedGlyph::draw` likely indicate that the character is not well formed and has a hole in one of its contours. I'll see if I can reproduce this and see whether it really is the font at fault.

**Comment by alexheretic** [comment]
This is quite old, but in current code the callback is always called with `_.abs()` or with a literal so this looks like it is no longer possible. I guess now this issue would cause incorrect drawing, if anyone is seeing that please create a new issue.
