### ISSUE TITLE
read font and output as either png or vec

### ISSUE THREAD

**Issue by kosinix** [redox-os/rusttype#33]
Hello. Is it possible to read a font, set it to a specific font size and output it as a png? or a vec containing pixels of RGBA sequence?

The reason Im asking is i have a lib that edits images and I want to incorporate writing texts on an image using rusttype. Is that possible? If so how to go about doing that?

(Sorry if its not a proper channel for this question but I cant find any way to contact the author.)

**Comment by icefoxen** [comment]
It's possible, but you basically have to read the glyphs the font provides and construct a string you want to produce, then rasterize the text to a (RGBA usually) bitmap yourself and then shove it through a png encoder.

**Comment by alexheretic** [comment]
I'll close as we even have an image example now: `cargo run --example image`
