### ISSUE TITLE
Text artifacts when running on Ubuntu 16.04

### ISSUE THREAD

**Issue by johnthagen** [redox-os/rusttype#35]
I've been developing a game with [Piston](http://www.piston.rs/) and decided to try it out on Ubuntu. So far there has been no problem with any of the text rendering on Windows or macOS, but on Ubuntu there are many problems with rendering.

<img width="515" alt="screen shot 2017-02-12 at 4 20 46 pm" src="https://cloud.githubusercontent.com/assets/10340167/22866152/55349996-f13f-11e6-8711-cc08bdc4eb97.png">

<img width="336" alt="screen shot 2017-02-12 at 4 22 20 pm" src="https://cloud.githubusercontent.com/assets/10340167/22866160/76518b84-f13f-11e6-9aaa-3225dbdf1f3d.png">

The source for the project with install instructions is here: https://github.com/johnthagen/rust-belt

Note: This was run from within a virtual machine using VMWare Fusion running on OSX.

**Comment by jackpot51** [comment]
What version of rusttype where you using?

**Comment by johnthagen** [comment]
The dependancies have certainly changed since I first reported this issue. I tried it again with the latest version of https://github.com/johnthagen/rust-belt on VMWare Fusion running an Ubuntu 16.04 VM.

I see fewer artifacts, but still some:

![screen shot 2017-09-21 at 10 37 43 am](https://user-images.githubusercontent.com/10340167/30701785-290964fa-9eb9-11e7-85c7-16cad28a7e96.png)


`rusttype` 0.2.1 is used as a dependency from `piston`.

**Comment by jackpot51** [comment]
Thanks

**Comment by alexheretic** [comment]
The missing glyph issue was fixed a while ago in the gpu_cache code. The glyphs rendering over each other is not a rusttype issue that I've seen and may well have a cause outside rusttype.

Was this raised at all with the piston text projects?

**Comment by johnthagen** [comment]
@alexheretic I don't recall reporting this issue anywhere else.

**Comment by alexheretic** [comment]
For what its worth the game text renders fine for me on Arch/x11, it's using `0.4.3` after semver update which doesn't have any known bugs.

I _think_ this is ok to close as I'm not aware of any remaining rusttype issues.
