### ISSUE TITLE
Get the postscript name of a font

### ISSUE THREAD

**Issue by fschutt** [redox-os/rusttype#44]
There is currently no way to get the postscript name of a font (i.e. "Roboto-Medium"). This is often very useful for identifying fonts. Is this currently planned?

**Comment by lo48576** [comment]
https://github.com/dylanede/stb_truetype-rs/pull/4
I've written a pull request for stb_truetype-rs (backend library of rusttype) but it is not merged.
I believe this PR is useful if someone implement font-name-related feature to rusttype.

**Comment by sharazam** [comment]
@lo48576 I somehow have the feeling this repository is not maintained anymore...

**Comment by fschutt** [comment]
https://github.com/redox-os/stb_truetype-rs/pull/4 is now merged, closing.
