### ISSUE TITLE
Support unscaled fonts

### ISSUE THREAD

**Issue by fschutt** [redox-os/rusttype#45]
Currently, you cannot get a fonts ascender / descender without scaling the font. Freetype as a `FT_NO_SCALE`, which just gives you the raw metrics for the font. There is a Glyph::unscaled() thing, but it doesn't help, really. The font itself has to be unscaled to get the ascender and descender correctly. 

The function `Font::v_metrics(&self, scale: Scale) -> VMetrics` should accept a `NoScale` or similar as the `Scale` parameter.

**Comment by sharazam** [comment]
This can easily be done by making a wrapper function for `Font.info.get_v_metrics()` which returns the unscaled information.

**Comment by sharazam** [comment]
Also there is no way to get the extents of an unscaled glyph, only a scaled one.

I'm working on it.
