### ISSUE TITLE
What is the status of the project?

### ISSUE THREAD

**Issue by ozkriff** [redox-os/rusttype#48]
@dylanede What are the current status and future plans of the project? Rusttype works fine right now, but it doesn't seem to be actively maintained for a long time.

**Comment by daboross** [comment]
There are also some PRs like #29, #24, #38 that, while not critical, would be good improvements if merged.

In addition, https://github.com/nothings/stb/blob/master/stb_truetype.h seems to have been majorly updated (I'm not sure what's changed), and re-rustifying that for the stb_truetype crate this depends on could be good. I'd attempt this myself if I had more knowledge of font rendering (and dylanede was interested).

**Comment by jackpot51** [comment]
I am requesting transfer to another maintainer, please read and comment here: https://github.com/dylanede/rusttype/issues/55

**Comment by jackpot51** [comment]
I have begun merging PRs and doing maintenance.
