### ISSUE TITLE
Missing glyphs when using the gpu cache

### ISSUE THREAD

**Issue by alexheretic** [redox-os/rusttype#52]
Hi I've recently developed [gfx_glyph](https://github.com/alexheretic/gfx-glyph) which uses this lovely library. I've noticed sometimes glyphs are be missing from the render, see below example of incorrect/correct render.

![missing-glyphs](https://user-images.githubusercontent.com/2331607/29562899-287fa14a-8733-11e7-86f2-83e868c7a77b.gif)

When using the PR code in #39 this issue does *not* occur. So that, or a similar, change would be great.

Fixed by #39.

**Comment by jackpot51** [comment]
How do you recommend this is solved? Are both #39 and #53 required for this issue?

**Comment by alexheretic** [comment]
Nope, #53 is a faster solution to the same issue.
