### ISSUE TITLE
Consider transferring to a new maintainer

### ISSUE THREAD

**Issue by jackpot51** [redox-os/rusttype#55]
This library is a critical part of the Rust ecosystem, and has had a number of good PR's that have gone unreviewed and unmerged. The last update was September, 2016, *one year ago*.

There are several ways that this library can be maintained for the future:

- Transfer repository and crates.io to Redox OS. We will take care of new development, issues, crate uploads, PR merges, and any other maintainer tasks
- Transfer to somebody else, who may do the same thing. Also give them the ability to upload new crates
- Add a new maintainer with Write or Admin permissions. You would maintain control, but the library would be able to continue development

**Comment by jackpot51** [comment]
Sorry to spam the open and unmerged PR's, but I thought it was necessary for the potential contributors to see and comment on this issue.

**Comment by alexheretic** [comment]
Unfortunately dylanede is currently unresponsive, which is a bit of a downer. If you / redox team want to take this lib forward you may need to simply fork & rename.

Worth mentioning that if this happens I would be willing to maintain the gpu-cache code myself (split off from the main code) if desired, since I already do within [gfx_glyph](https://github.com/alexheretic/gfx-glyph).

**Comment by bvssvni** [comment]
We are open to host this project under PistonDevelopers.

**Comment by dylanede** [comment]
Sorry for the delay and radio silence everyone. @jackpot51 I'm happy for the project to move to the Redox organisation, though perhaps with me kept on the owners list.

**Comment by jackpot51** [comment]
Thanks @dylanede 

How do you want to discuss this?

**Comment by dylanede** [comment]
Well, from what I can see on the cargo docs, is it just a case of me adding you as an owner using `cargo owner --add jackpot51`, and then you can add the redox github "team" (presuming there is one) as an owner, if you've got a team set up, using something like `cargo owner --add github:redox-os:owners`. Is that the case? And also you'd need to re-upload the repository under the redox organisation, instead of clicking fork, as that wouldn't allow issues to work in the new repo.

That sound about right?

**Comment by dylanede** [comment]
Oh, actually there appears to be a way of doing an actual transfer of a github repository. I guess that would make more sense.

**Comment by jackpot51** [comment]
Yes @dylanede . The `cargo owner --add jackpot51` would add me to the crates.io.

For github, you can transfer the repository in the settings tab. I will add you as an Admin

**Comment by dylanede** [comment]
I've transferred crate ownership, but I can't directly transfer the github repo to the redox-os organisation, only to you as an intermediary, so you'll have to move it.

**Comment by jackpot51** [comment]
Ok, sounds good.

**Comment by jackpot51** [comment]
@dylanede it is done. You have admin rights, and can modify the repository as before as well as add or remove collaborators. I will be going through some of the PRs and merging.

Thanks very much for helping us out!

**Comment by mitchmindtree** [comment]
Thanks a lot both @dylanede and @jackpot51! I've found rusttype super useful - nice to see the spark staying alive :+1:

**Comment by jackpot51** [comment]
@dylanede can we do the same thing with https://github.com/dylanede/stb_truetype-rs ?

**Comment by fschutt** [comment]
@jackpot51 Could you please take a look at merging https://github.com/redox-os/rusttype/pull/46 and  https://github.com/dylanede/stb_truetype-rs/pull/9 - or tell me what's wrong? See issue https://github.com/redox-os/rusttype/issues/45 - what am I doing wrong, why is there no response? These PRs are still open.

**Comment by jackpot51** [comment]
Unfortunately @fschutt , I do not have the ability to merge PRs on the stb_truetype repository. I still want @dylanede to transfer that repo to redox-os.

**Comment by fschutt** [comment]
You could still merge https://github.com/redox-os/rusttype/issues/44 though, it has nothing to do with stb_truetype.

**Comment by fschutt** [comment]
@jackpot51 I mean if @dylanede doesn't respond at all, there is always the option of a hard fork. It's not that I'd want this to happen, but development can't be continuously stalled because one maintainer doesn't merge any PRs anymore.

**Comment by jackpot51** [comment]
@fschutt I would consider moving the stb_truetype code directly into rusttype, thus allowing crates.io uploads.

Would you like to help out by making a PR with that?

**Comment by fschutt** [comment]
@jackpot51 Sure, I'll see what I can do.

**Comment by dylanede** [comment]
Sorry for forgetting to do this - I've set up the ownership transfer to you @jackpot51.

**Comment by jackpot51** [comment]
Thanks @dylanede - I very much appreciate it!

**Comment by jackpot51** [comment]
@dylanede - I also would like to be added as an owner here: https://crates.io/crates/stb_truetype

**Comment by dylanede** [comment]
I've sent the owner invite.

**Comment by jackpot51** [comment]
Thanks so much @dylanede !
