### ISSUE TITLE
0.3.0

### ISSUE THREAD

**Issue by jackpot51** [redox-os/rusttype#68]
Release a new version

**Comment by alexheretic** [comment]
@jackpot51 perhaps we should make this available now?

**Comment by jackpot51** [comment]
Yep, I will do so in a couple hours

**Comment by alexheretic** [comment]
Hey @jackpot51, sorry to keep pestering you I know you're busy. But I think we should bosh out rusttype 0.3.0 now, I'd like to release gfx_glyph's next version making use of the changes.

**Comment by jackpot51** [comment]
Sorry for forgetting, I have released 0.3.0 now.
