### ISSUE TITLE
How do I vertically position the glyphs?

### ISSUE THREAD

**Issue by Xyten** [redox-os/rusttype#73]
I'm trying to use this in combination with opengl to render a text.

I pre-cached each glyphs into a single texture (using PositionedGlyph::pixel_bounding_box() as their height and width), but am unable to properly position them since the VMetrics is per font instead of per glyph
.
![capture](https://user-images.githubusercontent.com/8429689/34684350-68ebca58-f4d7-11e7-89ed-d705930706d6.PNG)

The origin for the text is on the top left of the texture. How would one position the text properly ?

**Comment by Xyten** [comment]
I've found out that the vertical position information for each glyph is actually available on the bounding box (that is why it have min and max instead of only height and width).

I made it work with origin_transform.y - bb.height() - bb.max.y

![capture](https://user-images.githubusercontent.com/8429689/34704336-18485c98-f52b-11e7-82ea-c4992db130d7.PNG)

**Comment by alexheretic** [comment]
Look at `Font::layout` for an example of basic single-line layout. Two glyphs from the same font at the same y-position should already be correctly lined up, so just make sure not to lose this info after you draw them into your texture. Also see the gpu_cache code which does this correctly.
