### ISSUE TITLE
Panic in rasterizer.rs

### ISSUE THREAD

**Issue by Yatekii** [redox-os/rusttype#77]
Hi,

When I move text in my program, I get this panic:

```
RUST_BACKTRACE=1 cargo run --release test_data/kicad.lib test_data/kicad.sch                                                                                      130   gfx-rework 
   Compiling schema_parser v0.1.0 (file:///home/bastli/Programming/schema_renderer)
    Finished release [optimized] target(s) in 13.93 secs
     Running `target/release/schema_renderer test_data/kicad.lib test_data/kicad.sch`
thread 'main' panicked at 'internal error: entered unreachable code', /home/bastli/.cargo/registry/src/github.com-1ecc6299db9ec823/rusttype-0.3.0/src/rasterizer.rs:155:17
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
   6: <rusttype::rasterizer::CurveSliceIter as core::iter::iterator::Iterator>::next
   7: rusttype::rasterizer::rasterize
   8: gfx_glyph::gpu_cache::Cache::cache_queued
   9: <gfx_glyph::GlyphBrush<'font, R, F>>::draw_queued_with_transform
  10: <schema_renderer::drawables::text_drawable::TextDrawable as schema_renderer::drawables::Drawable>::draw
  11: <schema_renderer::drawables::group_drawable::GroupDrawable as schema_renderer::drawables::Drawable>::draw
  12: schema_renderer::main
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  15: __libc_start_main
  16: _start
```

Unfortunately I am not really familiar with the rusttype codebase so a fix by myself doesn't seem feasible ...

Best,
Yatekii

**Comment by alexheretic** [comment]
Reaching unreachable code is never good. 

To get to the bottom of this though we're going to need to gather a little more info.

Your trace shows this is a panic when trying to draw a particular glyph. Assuming determinism, if we create the same `PositionedGlyph` from the same font we'll be able to reproduce & fix the issue.

If possible can you provide two things:
- **The font ttf used**
- **The `PositionedGlyph` that caused the panic**

This glyph is a little harder for you to get... But you can ascertain by logging the glyph, this way:
* `git clone https://github.com/alexheretic/gfx-glyph` next to your project
* add to your Cargo.toml (to use local gfx-glyph)
    ```toml
    [patch.crates-io]
    gfx_glyph = { path = '../gfx-glyph' }
    ```
* edit _../gfx-glyph/src/gpu_cache.rs_, add to line 494 (just before the `glyph.draw` call)
  ```rust
  info!(
      "pre-draw: PositionedGlyph {{ id: {id}, scale: {scale:?}, position: {pos:?} }}",
      id = glyph.id().0,
      scale = glyph.scale(),
      pos = glyph.position(),
  );
  ```
* Run your scenario with `RUST_LOG=gfx_glyph=info` and record the last log before the panic.

**Comment by Yatekii** [comment]
Okay, so I tried to reproduce this but I wasn't able to thus far.

The font was Inconsolata-Regular, directly loaded from [Google](https://fonts.google.com/specimen/Inconsolata).

I had some changes to the codebase but tried to go back to the old state with git. But somehow it just wont trigger anymore. I keep on trying and will notify you as soon as it happens again.

Also, in the source head the `glyph.draw` call is not on line 494. Could that be possible? It's more like line 525 for me.

**Comment by alexheretic** [comment]
> It's more like line 525 for me.

Right you are, not sure where I got 494 from...

**Comment by alexheretic** [comment]
I'll close this for now, please re-open if/when anyone can reproduce.
