### ISSUE TITLE
0.3.1 breaks sem ver ?

### ISSUE THREAD

**Issue by thiolliere** [redox-os/rusttype#81]
I'm not completly sure about sem ver guidelines but the 0.3.1 break compilations of conrod because gpu_cache is now optionnal.

you can make default feature in cargo manifest: https://doc.rust-lang.org/cargo/reference/manifest.html

https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md

**Comment by mitchmindtree** [comment]
Yes, any conrod user that `cargo update`s right now is going to have a broken build due to this.

@jackpot51 If you could confirm whether you will yank this and publish `0.4` or keep it as is that would be a great help so I know what to do for conrod.

**Comment by jackpot51** [comment]
Understood - I will yank and publish 0.4. Sorry for the inconvenience

**Comment by jackpot51** [comment]
Done
