### ISSUE TITLE
Rusttype doesn't return errors

### ISSUE THREAD

**Issue by jimblandy** [redox-os/rusttype#84]
It would be nice if rusttype returned errors when it encountered data it can't handle, instead of simply returning `Option`. For example, `FontCollection::into_font` offers no way to distinguish between failure because the collection contains only one font and failure because the font data is ill-formed.

It seems like it would be idiomatic for Rusttype to have its own `Error` and `Result` types. `FontCollection::into_font` would return `Result<Font<'a>>`; `IntoFontsIter<'a>::Item` would be `Result<Font<'a>>`; and so on.

If the rusttype developers agree that this would be an improvement, I could work on this.

**Comment by jackpot51** [comment]
I think this would be good @jimblandy - thanks for the suggestion!

**Comment by jimblandy** [comment]
If anyone's curious, they can follow along as I mess around with this:
https://github.com/jimblandy/rusttype/tree/errors

**Comment by jimblandy** [comment]
@jackpot @alexheretic I have some changes done for this that cover `FontCollection`; I've included the `Error` type below. To see how it would go, I wrote patches for the ten most-downloaded dependencies of rusttype to adapt them to this API; that seemed fine.

I see that you're putting together an 0.5.0 release. I'll put together a PR for what I've got so far, so you can see if you'd like to include it. I need to rebase it past the rustfmt, so it'll take me a bit, but I should have it in an hour or two if I don't get distracted.

```
/// The type for errors returned by rusttype.
#[derive(Debug)]
pub enum Error {
    /// Font data presented to rusttype is not in a format that the library recognizes.
    UnrecognizedFormat,

    /// Font data presented to rusttype was ill-formed (lacking necessary
    /// tables, for example).
    IllFormed,

    /// The caller tried to access the `i`'th font from a `FontCollection`, but
    /// the collection doesn't contain that many fonts.
    CollectionIndexOutOfBounds,

    /// The caller tried to convert a `FontCollection` into a font via `into_font`,
    /// but the `FontCollection` contains more than one font.
    CollectionContainsMultipleFonts,
}
```

**Comment by alexheretic** [comment]
Sounds good! I don't think I'll finish messing about with the gpu_cache padding changes tonight anyway. So no big rush!

**Comment by jimblandy** [comment]
If it's all right, I'd like to close this issue now that rusttype does at least have an `Error` type and use it a bit. We can file more specific issues for APIs that ought to use `Error` as we identify them. But if we interpreted this issue as "rusttype should handle all errors ideally" it'd be sort of never-ending.
