### ISSUE TITLE
Expose font names from std_truetype::FontInfo

### ISSUE THREAD

**Issue by azriel91** [redox-os/rusttype#86]
I'd like to be able to read the font names from the `Font`, currently `info` is private and prevents external crates from accessing the font names.

I'll open a PR (#87) that returns `FontInfo#get_font_name_strings()` shortly; hope you don't mind :slightly_smiling_face:

**Comment by alexheretic** [comment]
This can be closed now if I understand correctly, please reopen otherwise.

**Comment by azriel91** [comment]
Yay a release! :tada: (was waiting on that)
